@startuml
'https://plantuml.com/sequence-diagram
title Local Weather Station - User registration
autonumber
actor User
participant WebServer
participant Database

User -> WebServer: Enter all registration details
activate User
activate WebServer
WebServer -> Database: Check the entered email
alt#Gold #LightBlue Email already exists
    WebServer -> User: Email already exists
else #LightGreen Email not in the database
    WebServer -> User: Email valid
    deactivate User
end
WebServer -> Database: Create user
activate Database
WebServer -> Database: Update user station subscriptions
WebServer -> Database: Update user notification preferences
deactivate Database
deactivate WebServer
WebServer -> User: Account created
deactivate User
@enduml