@startuml
'https://plantuml.com/sequence-diagram
title User Registration
autonumber
actor User
participant WebServer
participant Database

User -> WebServer: Enter all registration details
activate User
activate WebServer
WebServer -> Database: Check the entered email in database
activate Database
alt#Gold #LightBlue Email already exists
    Database -> WebServer: Email already exists
    WebServer -> User: Email already exists!
else #LightGreen Email does not exist
    Database -> WebServer: Email does not exist
WebServer -> Database: Create user
WebServer -> Database: Update user station subscriptions
WebServer -> Database: Update user notification preferences
deactivate Database
WebServer -> User: User registered
deactivate WebServer
deactivate User
end
@enduml