@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor user
participant User
participant Station
participant Sensor
participant Admin
Admin -> Station: Enable Station
user -> User: Subscribe to station
User -> Station: Attach as an observer
alt#Gold #LightBlue Update in sensor reading
    Sensor -> Station: Update the value
    alt#Gold #LightBlue Sensor values in critical range
        Station -> User: Alarm notify
        User -> user: Send email
    end
end

alt#Gold #LightBlue Notification time
    Station -> User: Notify sensor values
    User -> user: Send email with latest sensor data
end


@enduml