@startuml
'https://plantuml.com/sequence-diagram

autonumber
title Update Subscriptions
actor User
participant WebServer
participant Database
User -> WebServer: Enter Login credentials
activate User
activate WebServer
WebServer -> Database: Find user with credentials
activate Database
Database -> WebServer: Return user
WebServer -> User : Logged in
deactivate Database
deactivate WebServer
User -> WebServer: Update station subscriptions
activate WebServer
WebServer -> Database: Add or remove stations
WebServer -> User: Updated!
deactivate WebServer
@enduml