@startuml
left to right direction
actor Admin as A
actor User as U
actor "Weather Station" as W
package "Weather Monitoring System" {
  together {
      usecase "Register" as UC1
      usecase "Login" as UC2
      usecase "Update Profile" as UC3
  }
  together {
      usecase "Subscribe to a Weather Station" as UC4
      usecase "Unsubscribe from a Weather Station" as UC5
  }
  together {
      usecase "Interval Notify Users" as UC6
      usecase "Alarm Notify Users" as UC7
  }
  together {
      usecase "Enable Weather Station" as UC8
      usecase "Disable Weather Station" as UC9
  }
}
A --> UC2
U --> UC1
U --> UC2
U --> UC3
U --> UC4
U --> UC5
U -- UC6
U -- UC7
A --> UC8
A --> UC9
UC4 -- W
UC5 -- W
UC6 <-- W
UC7 <-- W
UC8 -- W
UC9 -- W
@enduml